obf-generation/regions/indexes.xml
The Netherlands split has been added but "out-commented" to make it possible to activate it at the right moment
=> Update regions; Add split Netherlands as inactivated set

OsmAndMapCreator/OsmAndMapCreator.iml, OsmAndMapCreator/src/net/osmand/BinaryMerger.java, OsmAndMapCreator/src/net/osmand/MainUtilities.java, OsmAndMapCreator/src/net/osmand/data/index/IndexUploader.java, OsmAndMapCreator/src/net/osmand/data/preparation/BinaryFileReference.java, OsmAndMapCreator/src/net/osmand/data/preparation/BinaryMapIndexWriter.java, OsmAndMapCreator/src/net/osmand/data/preparation/IndexCreator.java, OsmAndMapCreator/src/net/osmand/data/preparation/address/IndexAddressCreator.java
Do not merge — work in progress.
The major error — `getFilePointer()` always return `0`.
=> [WIP] Obf merge

OsmAndMapCreator/src/net/osmand/BinaryMerger.java
Difference (examples):
```
new                                                                        | old
----------------------------------------------------------------------------------------------------------------------------------------
'Рай Оленівка' 2 street(s):                                                | 'Рай Оленівка' 1 street(s):
| 'Рай-Оленівка' 1 street(s):
|
'Фащівка' [337604237], 0 street(s):                                        | 'Фащівка (Luhansk)' [337604237], 0 street(s):
'Фащівка' [337606150], 0 street(s):                                        | 'Фащівка (Luhansk)' [337606150], 0 street(s):
|
'Михайлівка (Luhansk)' [337660388], 0 street(s):                           | 'Михайлівка (Luhansk) (Luhansk)' [337660388], 0 street(s):
'Михайлівка (Luhansk)' …
```
=> OBF combine address index: do not rename cities in same region

OsmAndMapCreator/src/net/osmand/BinaryMerger.java
Group duplicates to any number of cities, not just around one of them.
=> OBF combine address index

OsmAndMapCreator/src/net/osmand/data/preparation/address/IndexAddressCreator.java
I've tested this by hand, looks like it works correctly and greatly reduces street duplicate count.
=> MapCreator: merge streets case insensitively

support-tools/ExceptionAnalyzer/src/main/java/net/osmand/exceptionanalyzer/DebugAnalyzer.java, support-tools/ExceptionAnalyzer/src/main/java/net/osmand/exceptionanalyzer/ExceptionAnalyzerMain.java
I've added another parsing strategy.
=> Paul's branch

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/MainUtilities.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/AbstractIndexPartCreator.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexCreator.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexCreatorSettings.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexRouteCreator.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexVectorMapCreator.java
need to add argument --add-region-tag to https://github.com/osmandapp/OsmAnd-misc/blob/master/osm-live/generate_hourly_osmand_diff.sh
=> add region tags #6415

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/travel/WikivoyageLangPreparation.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/wiki/WikiDatabasePreparation.java
=> Fix unhandled mark-up macroses

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexAddressCreator.java
Ignoring cities that never store to "city" table. Otherwise it is occur streets with NULL city in "street" table.
=> Index adress 10010

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/BinaryMapIndexWriter.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexPoiCreator.java
Diff between 26 and 24 zooms for precision results
=> Add diff between 26 and 24 zoom for precision results

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/wiki/CustomWikiModel.java
=> fix frameless caption

java-tools/OsmAndMapCreator/src/main/java/net/osmand/swing/MapPanel.java, java-tools/OsmAndMapCreator/src/main/java/net/osmand/swing/MapPointsLayer.java, java-tools/OsmAndMapCreator/src/main/java/net/osmand/swing/MapRouterLayer.java
=> Gradient colorization for route

java-tools/OsmAndMapCreator/src/main/java/net/osmand/swing/MapPanel.java, java-tools/OsmAndMapCreator/src/main/java/net/osmand/swing/MapPointsLayer.java, java-tools/OsmAndMapCreator/src/main/java/net/osmand/swing/MapRouterLayer.java
Added dialog what color cheme to use.
=> Added Grey OR Red, Yellow, Green color scheme

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/BinaryMapIndexWriter.java
Decreased mistake of 24 zoom. Such variant of calculation has less or equal mistake as was before.
Additional to visual test made mathematical test.
Before:
After:
=> Decrease mistake of 24 zoom

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexAddressCreator.java
исчезла из поиска улица Васильковская, дублика Васильківська
остальное не дубликаты - Нова Забунова suburb и его один дом также есть в основной улице
Васильківська и Велика Васильківська это разные улицы
12723 - теперь одна общая улица
=> join streets with similar names,1465, 12723

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexVectorMapCreator.java
Detect northest id for avoid hole on the roads between neighbour maps
=> Issue 13071

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexAddressCreator.java
Related issue and PR
https://github.com/osmandapp/OsmAnd/issues/12999
https://github.com/osmandapp/OsmAnd-tools/pull/440
=> Fix maps generation: Ireland, North Ireland, Colombia

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/osm/OsmcSymbol.java, java-tools/OsmAndMapCreatorUtilities/src/test/java/net/osmand/osm/MapRenderingTypesEncoderTest.java
[issue](https://github.com/osmandapp/OsmAnd-Issues/issues/1380)
=> osmc_empty_foreground_fix

java-tools/OsmAndServer/src/main/java/net/osmand/server/api/repo/DeviceSubscriptionsRepository.java, java-tools/OsmAndServer/src/main/java/net/osmand/server/controllers/pub/UserdataController.java, java-tools/OsmAndServerUtilities/src/main/java/net/osmand/live/subscriptions/UpdateSubscription.java
https://github.com/osmandapp/OsmAnd-Issues/issues/1395
=> iOS PRO subscription validate on fly

java-tools/OsmAndServer/src/main/java/net/osmand/server/api/services/OsmAndMapsService.java
Reverts osmandapp/OsmAnd-tools#489
=> Revert "remove duplicates map"

cpp-tools/map-viewer/CMakeLists.txt, cpp-tools/map-viewer/main.cpp
Related:
- https://github.com/osmandapp/OsmAnd-core/pull/303
- https://github.com/osmandapp/OsmAnd-iOS/pull/1948
=> Symbols elevation

cpp-tools/map-viewer/main.cpp
Added additional information about the current point of view
=> Show camera coordinates and height

java-tools/OsmAndServer/src/main/java/net/osmand/server/api/services/DownloadIndexesService.java
To issue https://github.com/osmandapp/OsmAnd-Issues/issues/1563
=> Add multyindex from several hosts for indexes.xml

cpp-tools/map-viewer/main.cpp
Changed type for camera coordinates
=> Change camera coordinates type

cpp-tools/map-viewer/main.cpp
=> Added detail levels

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexVectorMapCreator.java
To issue https://github.com/osmandapp/OsmAnd/issues/15483
=> Add center node for island with coastline

obf-generation/heightmap/generate_tile.sh
Use different output directory
=> Fix heightmap tile overlapping

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/maplegend/SvgMapLegendGenerator.java
Added new fields for icon and shield size.
Example:
`<icon name="Traffic mirror" tag="highway" value="traffic_mirror" icon_size="22" shield_size="30" />`
=> force string format for floats

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/NativeJavaRendering.java
Adding able to read addons file from MapCreator.
To issue https://github.com/osmandapp/OsmAnd/issues/15916
=> Issue 15916

cpp-tools/map-viewer/main.cpp
=> Attach geotiff heightmap provider

obf-generation/heightmap/generate_tile.sh
Don't flip coordinates second time
=> Fix wrong W and S coordinates

obf-generation/heightmap/generate_tile.sh
Fix negative coordinates in file names
=> Make positive coordinates for file name

obf-generation/heightmap/generate_tile.sh, obf-generation/heightmap/tiler.py
Generate edge tiles for heightmaps
=> Allow edge tiles generation for heightmaps

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/util/TileListsForRegions.java, obf-generation/heightmap/tiler.py
Add directories for heightmap tiles
=> Create directories for generated tiles

obf-generation/heightmap/tiler.py
Transfer geotiff metainfo to tiles
=> Fix geotiff metainfo transfer

java-tools/OsmAndServer/src/main/java/net/osmand/server/api/services/RoutingService.java, java-tools/OsmAndServer/src/main/java/net/osmand/server/utils/WebGpxParser.java
```
<rte>
<rtept lat="50.4477661" lon="30.5220258">
<extensions>
<osmand:profile>car</osmand:profile>
<osmand:trkpt_idx>0</osmand:trkpt_idx>
</extensions>
</rtept>
<rtept lat="50.448907" lon="30.5202234">
<extensions>
<osmand:profile>car</osmand:profile>
<osmand:trkpt_idx>38</osmand:trkpt_idx>
</extensions>
</rtept>
</rte>
```
```
<osmand:route>
<segment id="1125736454" length="2" startTrkptIdx="0" segmentTime="0.22" speed="13.89" turnType="C" types="0,1,2,3,4,5,6,7,8,9,10,11,12" names="41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58" />
<segment id="1125740459" length="3" startTrkptIdx="1" segmentTime="28.81" speed="11.48" types="0,2,3,4,5,6,7,9,10,13,12" pointTypes=";14,15,16;17" names="41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58" />
<segment id="1125736457" length="2" …
```
=> fix create gpx with routing web

java-tools/OsmAndServer/src/main/java/net/osmand/server/api/services/DownloadIndexesService.java, java-tools/OsmAndServer/src/main/java/net/osmand/server/controllers/pub/DownloadIndexController.java
To issue https://github.com/osmandapp/OsmAnd/issues/16481
=> Use cache for request HEAD /download

java-tools/OsmAndServer/src/main/java/net/osmand/server/controllers/pub/UserdataController.java
Logs issue https://github.com/osmandapp/OsmAnd-Issues/issues/1944
=> Add logs for subscription

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/MainUtilities.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/BinaryInspector.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/BinaryMerger.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/diff/ObfDiffGenerator.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/diff/ObfFileInMemory.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/BinaryMapIndexWriter.java
To issue https://github.com/osmandapp/OsmAnd-Issues/issues/1885
=> Add OsmAndOwner to obf

java-tools/OsmAndServer/src/main/java/net/osmand/server/api/services/PromoService.java
=>  fix NullPointerException

db/sql_changeset_schema, java-tools/OsmAndServer/src/main/java/net/osmand/server/api/services/UserdataService.java, java-tools/OsmAndServer/src/main/java/net/osmand/server/controllers/user/MapApiController.java
Reverts osmandapp/OsmAnd-tools#627
=> Revert "add get user by email"

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/OsmDbCreator.java
To issue https://github.com/osmandapp/OsmAnd/issues/17047
=> Replace duplicated nodes

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/util/WeatherPrepareRasterSqliteRegions.java
Use correct tile numbering in weather region tiles
=> Use correct tile numbering in weather region tiles

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexCreationContext.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexCreator.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexPoiCreator.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexRouteCreator.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexRouteRelationCreator.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexTransportCreator.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexVectorMapCreator.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/osm/MapRoutingTypes.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/osm/RelationTagsPropagation.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/util/FixBasemapRoads.java
To issue https://github.com/osmandapp/OsmAnd/issues/17310
=> Refactor routing types

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexPoiCreator.java
To issue https://github.com/osmandapp/OsmAnd/issues/17335
=> Add amenity order for obf creation

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/osm/MapRenderingTypesEncoder.java
To issue https://github.com/osmandapp/OsmAnd/issues/18008
=> Fix possible problem with convert tags by rendering_types.xml

cpp-tools/map-rasterizer/main.cpp
Add arguments to support JSON files generation in map rasterizer
=> Support JSON report in map rasterizer

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/MainUtilities.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/wiki/CommonsWikimediaPreparation.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/wiki/WikiDatabasePreparation.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/wiki/wikidata/ArticleMapper.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/wiki/wikidata/WikiDataHandler.java
Part of task https://github.com/osmandapp/OsmAnd/issues/13926
=> Collect wikidata properties P18, P373

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/wiki/CommonsWikimediaPreparation.java
To issue https://github.com/osmandapp/OsmAnd/issues/13926
=> Improve database structure

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexCreator.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexRouteCreator.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/PropagateToNodes.java
=> Add propagateToNodes for all sections

java-tools/build.gradle
To issue https://github.com/osmandapp/OsmAnd/issues/18143
=> Add -Deyepiece=path_to_eyepiece_standalone to test via gradlew

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexCreator.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/OsmDbAccessor.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/OsmDbCreator.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/PropagateToNodes.java
=> Propagate to nodes, add border type

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/PropagateToNodes.java
=> Add propagateIfTag propagateIfValue

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/PropagateToNodes.java
=> Improve propagate to nodes for border type

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/wiki/WikipediaByCountryDivider.java
To issue https://github.com/osmandapp/OsmAnd/issues/13926
=> Change wikipedia generation parameters

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/diff/DiffParser.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/diff/ObfDiffGenerator.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/diff/RelationDiffGenerator.java, obf-generation/osm-live/generate_obf_start_end.sh
To issues
https://github.com/osmandapp/OsmAnd/issues/18153
https://github.com/osmandapp/OsmAnd/issues/18722
=> Live update. Fix deleted relation members processing

java-tools/OsmAndServer/src/main/java/net/osmand/server/api/repo/PremiumUsersRepository.java, java-tools/OsmAndServer/src/main/java/net/osmand/server/api/services/UserdataService.java, java-tools/OsmAndServer/src/main/java/net/osmand/server/controllers/pub/UserdataController.java, java-tools/OsmAndServer/src/main/java/net/osmand/server/controllers/user/MapApiController.java
Reverts osmandapp/OsmAnd-tools#772
=> Revert "fix user api"

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/wiki/wikidata/ArticleMapper.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/wiki/wikidata/WikiDataHandler.java
To issue https://github.com/osmandapp/OsmAnd/issues/19329
=> Add property depict P180 to Wikidata

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/osm/MapRenderingTypesEncoder.java
To issue https://github.com/osmandapp/OsmAnd/issues/19309
=> Fix calculateIntegrity for bicycle routing

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexTransportCreator.java
Reverts osmandapp/OsmAnd-tools#815
=> Revert "Subway stations on click don't display and suggest subway lanes"

obf-generation/osm-live/generate_obf_start_end.sh
To issue https://github.com/osmandapp/OsmAnd/issues/19201
=> Add obf size checker to live-update process

java-tools/OsmAndServer/src/main/java/net/osmand/server/monitor/OsmAndServerMonitorTasks.java
This reverts commit 3ac1733a9c929f903340523ed0643f571f8107f7.
=> Revert "Remove dl4 from monitoring (temporarily)"

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/BinaryMapIndexWriter.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexPoiCreator.java
To issue https://github.com/osmandapp/OsmAnd/issues/16397
=> Top index generation for additional tags

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/osm/MapRenderingTypesEncoder.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/osm/OsmcSymbol.java
To issue https://github.com/osmandapp/OsmAnd/issues/19617
=> Add tags for OSMC for no name and no ref

java-tools/OsmAndServerUtilities/src/main/java/net/osmand/data/changeset/CalculateOsmChangesets.java
=> Live data changesets download

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexPoiCreator.java, java-tools/OsmAndServerUtilities/src/main/java/net/osmand/data/changeset/CalculateOsmChangesets.java
To issue https://github.com/osmandapp/OsmAnd/issues/16397
=> Add lang support for top_index

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/BinaryInspector.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/BinaryMapIndexWriter.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/CityDataStorage.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexAddressCreator.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexCreator.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexPoiCreator.java
To issue [show city next to search result](https://github.com/osmandapp/OsmAnd/issues/2993)
=> Add city (tag groups) to poi section

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/NativeJavaRendering.java, java-tools/OsmAndServer/src/main/java/net/osmand/server/api/services/OsmAndMapsService.java, java-tools/OsmAndServer/src/main/java/net/osmand/server/controllers/pub/GeotiffTileController.java
Use native GDAL library to generate hillshade/slope/altitude terrain rasters
=> Use GDAL to generate terrain rasters

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/PropagateToNodes.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/osm/MapRenderingTypesEncoder.java
=> Fix propagate after entity_convert

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexPoiCreator.java
To issue https://github.com/osmandapp/OsmAnd/issues/2993
=> Fix show cities in search

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/BinaryMerger.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexPoiCreator.java
To issue https://github.com/osmandapp/OsmAnd/issues/2993
Depends from https://github.com/osmandapp/OsmAnd/pull/21079
=> Fix merge tagGroups for country obf

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/osm/MapRenderingTypesEncoder.java
To issue https://github.com/osmandapp/OsmAnd/issues/7408
=> Add ele_feet

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexVectorMapCreator.java
To issue https://github.com/osmandapp/OsmAnd/issues/8159
=> Add osmand_poi_lat_lon for multipoygons boundaries

obf-generation/osm-live/get_hourly_diff_osm.sh
To issue https://github.com/osmandapp/OsmAnd/issues/21304
=> Catch osm3s_query errors in get_hourly_diff_osm.sh

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/PropagateToNodes.java
To issue https://github.com/osmandapp/OsmAnd-Issues/issues/2790
=> Fix propagate to nodes

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/diff/DiffParser.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/diff/ObfDiffGenerator.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/diff/RelationDiffGenerator.java
To issue https://github.com/osmandapp/OsmAnd/issues/21561
=> Fix live updates

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexPoiCreator.java
To issue https://github.com/osmandapp/OsmAnd/issues/21547
=> Add world brands

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexAddressCreator.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexPoiCreator.java
To issue https://github.com/osmandapp/OsmAnd/issues/11709
=> Add arabic normalizer for search

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexPoiCreator.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexVectorMapCreator.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/OsmDbAccessor.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/OsmDbAccessorContext.java
To issue https://github.com/osmandapp/OsmAnd/issues/21248
=> Extract climbing area center for POI

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexPoiCreator.java
To issue https://github.com/osmandapp/OsmAnd/issues/21120
=> Make same id for basemap POI

java-tools/OsmAndMapCreator/src/main/java/net/osmand/swing/OsmExtractionUI.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexCreator.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexRouteRelationCreator.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexVectorMapCreator.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/OverpassFetcher.java
To issue https://github.com/osmandapp/OsmAnd/issues/16808
=> Add date to overpass query

java-tools/OsmAndServer/src/main/java/net/osmand/server/utils/WebGpxParser.java
https://github.com/osmandapp/web/issues/724
=> fix tracks with empty route types

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexPoiCreator.java
Depends from https://github.com/osmandapp/OsmAnd/pull/22243
=> Fix superroute center

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/diff/ObfFileInMemory.java
To issue https://github.com/osmandapp/OsmAnd/issues/22205
=> Fix live-updates POI order

obf-generation/contours/V4/make-contour-tile-mt.sh
https://github.com/osmandapp/OsmAnd/issues/21738
=> Merge and cropp tiles during contour generation

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexPoiCreator.java
To issue https://github.com/osmandapp/OsmAnd/issues/21993
=> Improve generate id for POI

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/router/tester/RandomRouteEntry.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/router/tester/RandomRouteGenerator.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/router/tester/RandomRouteTester.java
0 = success
1 = any failed
2 = any deviated (default >=1%, set by --red=N in command line)
=> Add exit codes (success, failed, deviated) to RandomRouteTester

weather/download_weather.sh
To issue https://github.com/osmandapp/OsmAnd-Issues/issues/3045
=> Fix ECMWF download

python/translation/translate_docs.py
Order languages A-Z by ISO-code (English is 1st)
https://github.com/osmandapp/OsmAnd-Issues/issues/2903#issuecomment-3082520701
=> sort-langs

python/support/Zendesk.py
Add Check attachment in user request which is initiated the ticket to skip it in auto_reply logic.
=> Check attachment in user request fix

python/translation/Readme.md, python/translation/translate_docs.py, python/translation/translate_docs.sh
- Specific prompt per lang_code is added especially for Arabic
- Adding `--force flag` for translation mechanism
- Readme update
https://github.com/osmandapp/OsmAnd-Issues/issues/2903
=> translation-specific-prompt

python/lib/OpenAIClient.py, python/translation/translate_docs.py, python/translation/translate_docs.sh
1. safe_max_tokens is made more smart
2. Number of completions is increased to 2 attempts
3. Adding LLM_TIMEOUT=360 and MODEL_TOP_P=1
=> Max token fix

java-tools/OsmAndServer/src/main/java/net/osmand/server/controllers/pub/UserdataController.java
https://github.com/osmandapp/OsmAnd-Issues/issues/3082
=> Hotfix discardPreviousAccountOrderId for new users

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexRouteRelationCreator.java
https://github.com/osmandapp/OsmAnd-Issues/issues/2976
=> Add node_network in IndexRouteRelationCreator.java

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/BinaryInspector.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/OsmGpxWriteContext.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexPoiCreator.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexRouteRelationCreator.java
https://github.com/osmandapp/OsmAnd/issues/22226
=> Implement collectElevationStatsForWays for v2 routes

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexPoiCreator.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexRouteRelationCreator.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexVectorMapCreator.java
https://github.com/osmandapp/OsmAnd-Issues/issues/2976
=> Hotfix: skip proposed routes, require mandatory relation prefix in tags

java-tools/OsmAndServer/src/main/java/net/osmand/server/SearchTestRepositoryConfiguration.java, java-tools/OsmAndServer/src/main/java/net/osmand/server/api/searchtest/DataService.java, java-tools/OsmAndServer/src/main/java/net/osmand/server/api/searchtest/PolyglotEngine.java, java-tools/OsmAndServer/src/main/java/net/osmand/server/api/searchtest/ReportService.java, java-tools/OsmAndServer/src/main/java/net/osmand/server/api/searchtest/repo/SearchTestCaseRepository.java, java-tools/OsmAndServer/src/main/java/net/osmand/server/api/searchtest/repo/SearchTestDatasetRepository.java, java-tools/OsmAndServer/src/main/java/net/osmand/server/api/searchtest/repo/SearchTestRunRepository.java, java-tools/OsmAndServer/src/main/java/net/osmand/server/api/services/SearchTestService.java, java-tools/OsmAndServer/src/main/java/net/osmand/server/controllers/pub/SearchTestController.java
1. Generation column order fix
2. Report CSV upload fix
3. Cleanup fix
4. Make Datasets in single table fix
https://github.com/osmandapp/OsmAnd-Issues/issues/2905
=> search-test-gen-fix

java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexCreationContext.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexPoiCreator.java, java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexRouteRelationCreator.java
https://github.com/osmandapp/OsmAnd/issues/22226
=> Apply collectElevationStatsForWays to ClickableWay

python/translation/translate_docs.py
https://github.com/osmandapp/OsmAnd-Issues/issues/2903
=> Adding prev_content to prompt

python/translation/translate_docs.py
=> body_lines fix

java-tools/OsmAndServer/src/main/java/net/osmand/server/api/searchtest/BaseService.java, java-tools/OsmAndServer/src/main/java/net/osmand/server/api/searchtest/DataService.java, java-tools/OsmAndServer/src/main/java/net/osmand/server/api/searchtest/MapDataObjectFinder.java, java-tools/OsmAndServer/src/main/java/net/osmand/server/api/searchtest/ReportService.java, java-tools/OsmAndServer/src/main/java/net/osmand/server/api/services/SearchService.java, java-tools/OsmAndServer/src/main/java/net/osmand/server/api/services/SearchTestService.java, java-tools/OsmAndServer/src/main/java/net/osmand/server/controllers/pub/SearchTestController.java
- **Adding rerun, res_id link fix**
- **byTag fix**
- **Comparison report fix**
- **Dup count**
- **Dup minDistance fix**
https://github.com/osmandapp/OsmAnd-Issues/issues/2905#issuecomment-3346747430
=> search-test-back-v2.4

java-tools/OsmAndServer/src/main/java/net/osmand/server/api/services/SearchTestService.java
=> search-test-rerun-fix

python/translation/translate_docs.py
Partial MDX source-hash fix
https://github.com/osmandapp/OsmAnd-Issues/issues/2903
=> Partial MDX source-hash fix
